name: 'Coverage monitor'
description: 'A GitHub Action that monitor coverage.'
branding:
  icon: "check"
  color: "green"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret."
    required: true
  clover-file:
    description: "Path to Clover XML file."
    required: true
  base-clover-file:
    description: "Path to base Clover XML file. If specified then action won't try to download file from S3"
    required: false
  diff-tolerance:
    description: "Tolerance for coverage drop"
    required: false
    default: '0'
  ignore-missing-base:
    description: "Do not throw an error if base coverage file is missing"
  s3-bucket:
    description: "AWS S3 Bucket name"
  s3-access-key-id:
    description: "AWS S3 Access Key Id"
  s3-secret-access-key:
    description: "AWS S3 Secret Access Key"
  s3-key-prefix:
    description: "S3 key prefix for coverage report storage inside bucket. Default `coverage/${repository.full_name}`"
  check:
    description: "Whether check the coverage thresholds."
    required: false
    default: 'true'
  comment:
    description: "Whether comment the coverage report."
    required: false
    default: 'true'
  threshold-alert:
    description: "Mark the build as unstable when coverage is less than this threshold."
    required: false
    default: '50'
  threshold-warning:
    description: "Warning when coverage is less than this threshold."
    required: false
    default: '90'
  status-context:
    description: "A string label to differentiate this status from the status of other systems."
    required: false
    default: 'Coverage Report'
  comment-context:
    description: "A string label to differentiate the comment posted by this action."
    required: false
    default: 'Coverage Report'
  comment-mode:
    description: "A mode for comments, supported: `replace`, `update` or `insert`."
    required: false
    default: 'replace'
runs:
  using: 'node16'
  main: 'dist/index.js'
